-- mysql -u root -p < database/schema.sql

DROP DATABASE IF EXISTS reviews;

CREATE DATABASE reviews;

USE reviews;

-- CREATE TABLE users (
--   id INT AUTO_INCREMENT,
--   userId INT,
--   username VARCHAR(25),
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE products (
--   id INT AUTO_INCREMENT,
--   productId INT,
--   productName VARCHAR(100),
--   PRIMARY KEY (id)
-- );

CREATE TABLE reviews (
  id INT AUTO_INCREMENT,
  -- userId INT,
  -- productId INT,
  username VARCHAR(255),
  productName VARCHAR(255),
  reviewText VARCHAR(1000),
  reviewDate DATE DEFAULT (CURRENT_DATE),
  broadAgeAppeal INT,
  lengthOfPlay INT,
  quality INT,
  value INT,
  average DECIMAL(3, 2),
  -- FOREIGN KEY (userId)
  --   REFERENCES users(id),
  -- FOREIGN KEY (productId)
  --   REFERENCES products(id),
  PRIMARY KEY (id)
);

-- INSERT INTO users (userId, username) values (10001, 'maxeinhorn');
-- INSERT INTO users (userId, username) values (10002, 'maximus');
-- INSERT INTO users (userId, username) values (10003, 'maximillius');
-- INSERT INTO users (userId, username) values (10004, 'maximillian');
-- INSERT INTO users (userId, username) values (10005, 'maxwell');
-- INSERT INTO users (userId, username) values (10006, 'maximusprime');
-- INSERT INTO users (userId, username) values (10007, 'max');


-- INSERT INTO products (productID, productName) values (100001, 'Settlers of Catan');
-- INSERT INTO products (productID, productName) values (100002, 'Settlers of Bhutan');
-- INSERT INTO products (productID, productName) values (100003, 'Settlers of Gadol');
-- INSERT INTO products (productID, productName) values (100004, 'Settlers of Mars');
-- INSERT INTO products (productID, productName) values (100005, 'Settlers of Antarctica');
-- INSERT INTO products (productID, productName) values (100006, 'Settlers of Catalan');

-- INSERT INTO reviews (reviewText, reviewdate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Such a fun game!', '2020-12-1', 5, 4, 5, 4, 4);
-- INSERT INTO reviews (reviewText, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Came in empty box', 1, 1, 2, 1, 1.2);
-- INSERT INTO reviews (reviewText, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Meh', 3, 4, 2, 3, 3);

INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Western lowland gorilla',  'Settlers of Catan',  'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',  '2020-04-29',  5,  2,  3,  4,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Flightless cormorant',  'Settlers of Catan',  'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',  '2020-09-20',  3,  4,  1,  3,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Roller, lilac-breasted',  'Settlers of Catan',  'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',  '2020-03-04',  3,  1,  2,  4,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Wallaby, river',  'Settlers of Catan',  'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',  '2020-07-09',  4,  5,  3,  1,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Whale, baleen',  'Settlers of Catan',  'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',  '2019-09-06',  2,  2,  2,  2,  2);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Cobra (unidentified)',  'Settlers of Catan',  'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',  '2019-09-16',  5,  1,  2,  1,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Goose, egyptian',  'Settlers of Catan',  'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.',  '2020-10-09',  1,  5,  3,  5,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Australian pelican',  'Settlers of Catan',  'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',  '2020-01-04',  5,  5,  2,  5,  4.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Common wallaroo',  'Settlers of Catan',  'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',  '2020-08-15',  4,  5,  2,  1,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Blue crane',  'Settlers of Catan',  'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',  '2020-03-19',  4,  3,  2,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Monster, gila',  'Settlers of Catan',  'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',  '2019-09-05',  3,  5,  2,  1,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Otter, small-clawed',  'Settlers of Catan',  'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',  '2020-11-09',  1,  4,  5,  5,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Otter, cape clawless',  'Settlers of Catan',  'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',  '2020-10-13',  3,  3,  2,  1,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Camel, dromedary',  'Settlers of Catan',  'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',  '2020-04-13',  2,  4,  5,  5,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Lizard, giant girdled',  'Settlers of Catan',  'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',  '2019-12-29',  4,  4,  1,  1,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Rhea, common',  'Settlers of Catan',  'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.',  '2019-11-30',  3,  3,  3,  1,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('White-browed owl',  'Settlers of Catan',  'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',  '2020-01-30',  3,  3,  2,  3,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Emerald-spotted wood dove',  'Settlers of Catan',  'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',  '2020-01-19',  1,  3,  2,  4,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Lizard, desert spiny',  'Settlers of Catan',  'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',  '2020-10-04',  3,  4,  5,  5,  4.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Groundhog',  'Settlers of Catan',  'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.',  '2019-12-30',  4,  2,  5,  3,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('African wild cat',  'Settlers of Catan',  'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',  '2019-10-19',  4,  5,  1,  3,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Crane, blue',  'Settlers of Catan',  'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',  '2019-11-14',  2,  4,  4,  2,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('African lion',  'Settlers of Catan',  'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',  '2019-11-06',  4,  4,  2,  1,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Flamingo, roseat',  'Settlers of Catan',  'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',  '2019-10-16',  2,  4,  1,  2,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Ring-tailed coatimundi',  'Settlers of Catan',  'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',  '2020-10-31',  3,  2,  3,  2,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Grouse, sage',  'Settlers of Catan',  'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',  '2019-11-05',  3,  2,  1,  4,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Cottonmouth',  'Settlers of Catan',  'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',  '2020-02-20',  5,  2,  2,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Francolin, swainsons',  'Settlers of Catan',  'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.',  '2020-09-25',  3,  3,  2,  1,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Turtle, eastern box',  'Settlers of Catan',  'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',  '2020-11-07',  3,  1,  2,  4,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Grenadier, purple',  'Settlers of Catan',  'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',  '2020-10-05',  2,  4,  1,  2,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Squirrel, thirteen-lined',  'Settlers of Catan',  'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',  '2020-04-26',  1,  1,  1,  4,  1.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Red-tailed cockatoo',  'Settlers of Catan',  'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',  '2019-11-13',  5,  1,  1,  5,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Small-clawed otter',  'Settlers of Catan',  'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',  '2019-09-20',  1,  5,  1,  2,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Baboon, yellow',  'Settlers of Catan',  'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',  '2020-10-17',  5,  3,  5,  3,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Gull, pacific',  'Settlers of Catan',  'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',  '2020-08-23',  3,  3,  5,  5,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Stork, marabou',  'Settlers of Catan',  'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.',  '2019-11-27',  5,  5,  1,  2,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Masked booby',  'Settlers of Catan',  'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',  '2019-10-29',  3,  4,  1,  4,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Little brown dove',  'Settlers of Catan',  'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.',  '2020-10-29',  2,  5,  4,  1,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Mongoose, banded',  'Settlers of Catan',  'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',  '2020-02-14',  1,  4,  4,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Indian giant squirrel',  'Domainer',  'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',  '2020-10-19',  5,  5,  2,  5,  4.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Bear, sloth',  'Rank',  'Vivamus vel nulla eget eros elementum pellentesque.',  '2020-04-20',  2,  5,  2,  5,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Owl, australian masked',  'Quo Lux',  'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',  '2020-06-29',  3,  1,  2,  1,  1.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Sheep, stone',  'Alphazap',  'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.',  '2020-11-05',  5,  1,  1,  3,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Lechwe, kafue flats',  'Y-Solowarm',  'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',  '2019-09-23',  5,  4,  2,  2,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Python (unidentified)',  'Veribet',  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',  '2020-11-06',  4,  1,  5,  1,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Shrike, crimson-breasted',  'Voltsillam',  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',  '2019-10-25',  5,  3,  2,  3,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Stork, greater adjutant',  'Stronghold',  'Mauris lacinia sapien quis libero.',  '2020-06-10',  1,  4,  5,  5,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Striped skunk',  'Stim',  'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.',  '2020-10-14',  5,  4,  3,  3,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Greater blue-eared starling',  'Mat Lam Tam',  'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.',  '2019-12-07',  5,  5,  2,  1,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Spider, wolf',  'Cardify',  'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',  '2019-10-01',  2,  2,  2,  3,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Southern screamer',  'Ronstring',  'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',  '2020-05-04',  5,  2,  1,  2,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Bustard, kori',  'Treeflex',  'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',  '2020-10-05',  2,  4,  2,  2,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Blue fox',  'Voyatouch',  'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.',  '2020-03-20',  1,  2,  1,  3,  1.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Bird, black-throated butcher',  'Bigtax',  'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',  '2020-05-10',  4,  5,  1,  2,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Cat, jungle',  'Span',  'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',  '2020-10-07',  5,  2,  2,  5,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Stork, white-necked',  'Cardify',  'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',  '2020-05-03',  2,  1,  3,  5,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Eleven-banded armadillo (unidentified)',  'Prodder',  'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',  '2020-06-22',  4,  3,  4,  5,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Anteater, giant',  'Stronghold',  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',  '2020-08-05',  5,  1,  4,  5,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Shrike, common boubou',  'Keylex',  'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',  '2020-03-08',  3,  4,  4,  1,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Reindeer',  'Temp',  'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',  '2020-07-13',  5,  5,  4,  5,  4.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Bear, american black',  'Vagram',  'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.',  '2019-12-27',  1,  4,  5,  1,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Woylie',  'Rank',  'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',  '2020-09-11',  5,  5,  4,  1,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('African jacana',  'Namfix',  'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',  '2020-08-28',  5,  2,  2,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Buffalo, american',  'Trippledex',  'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.',  '2020-10-19',  3,  2,  3,  3,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Ground monitor (unidentified)',  'Regrant',  'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',  '2020-01-08',  2,  5,  3,  3,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Heron, giant',  'Zathin',  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.',  '2020-06-20',  5,  1,  2,  3,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Glider, squirrel',  'Subin',  'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',  '2019-11-18',  3,  2,  5,  4,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('African elephant',  'Zontrax',  'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',  '2020-02-10',  4,  3,  2,  3,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Siskin, pine',  'Tempsoft',  'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',  '2020-09-11',  5,  5,  2,  4,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Striped hyena',  'Job',  'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',  '2019-10-11',  2,  1,  4,  4,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Elephant, african',  'Tres-Zap',  'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',  '2020-03-28',  2,  5,  2,  2,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Impala',  'Y-find',  'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',  '2020-04-07',  2,  5,  5,  3,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Bandicoot, long-nosed',  'Aerified',  'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',  '2020-07-15',  3,  3,  4,  4,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Weaver, lesser masked',  'Latlux',  'Praesent blandit lacinia erat.',  '2019-10-15',  1,  3,  4,  4,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('American woodcock',  'Vagram',  'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',  '2020-08-23',  5,  3,  2,  1,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Burrowing owl',  'It',  'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',  '2019-09-28',  1,  5,  5,  5,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Deer, savannah',  'Keylex',  'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',  '2019-12-11',  5,  2,  3,  4,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Short-beaked echidna',  'Zontrax',  'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',  '2019-12-15',  5,  4,  3,  1,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Pied avocet',  'Biodex',  'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',  '2019-10-23',  3,  2,  1,  3,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Malay squirrel (unidentified)',  'Biodex',  'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.',  '2019-10-31',  2,  2,  3,  3,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Beaver, american',  'It',  'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',  '2019-09-20',  3,  2,  2,  2,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Loris, slender',  'Subin',  'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',  '2019-11-05',  3,  1,  5,  1,  2.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Southern elephant seal',  'Flexidy',  'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.',  '2019-12-07',  2,  2,  4,  4,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Hippopotamus',  'Regrant',  'Mauris ullamcorper purus sit amet nulla.',  '2020-04-02',  4,  4,  4,  5,  4.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Chacma baboon',  'Y-find',  'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',  '2019-09-15',  4,  5,  3,  2,  3.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('North American river otter',  'Veribet',  'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',  '2019-11-05',  1,  2,  3,  2,  2);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Blesbok',  'Duobam',  'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',  '2019-12-18',  3,  5,  4,  3,  3.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Indian giant squirrel',  'Ronstring',  'Suspendisse potenti.',  '2019-09-14',  1,  3,  2,  3,  2.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Common mynah',  'Bitwolf',  'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',  '2019-11-17',  1,  4,  2,  1,  2);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Red meerkat',  'Y-Solowarm',  'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',  '2019-10-23',  4,  1,  4,  3,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Native cat',  'Zaam-Dox',  'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',  '2019-12-02',  5,  3,  1,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Red-breasted nuthatch',  'Bitchip',  'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',  '2020-06-18',  3,  3,  5,  5,  4);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Monster, gila',  'Matsoft',  'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',  '2020-07-02',  3,  2,  4,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Spider, wolf',  'Temp',  'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.',  '2020-01-29',  5,  2,  3,  3,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Boar, wild',  'Voltsillam',  'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',  '2020-04-30',  4,  2,  4,  2,  3);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Boa, mexican',  'Wrapsafe',  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.',  '2020-05-11',  2,  1,  4,  4,  2.75);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Red howler monkey',  'Zathin',  'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',  '2020-01-04',  5,  3,  5,  5,  4.5);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Steller sea lion',  'Konklab',  'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',  '2019-11-28',  1,  3,  5,  4,  3.25);
INSERT INTO reviews (username, productName, reviewText, reviewDate, broadAgeAppeal, lengthOfPlay, quality, value, average) values ('Skimmer, four-spotted',  'Domainer',  'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',  '2020-04-15',  1,  1,  3,  1,  1.5);